In [203]:
import pandas as pd

In [204]:
data=pd.read_csv('movies_metadata.csv')

C:\Users\SREEJA\AppData\Local\Temp\ipykernel_4008\3199850993.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('movies_metadata.csv')

In [205]:
data.shape

(45466, 24)

In [206]:
data.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

##### Factors that determine the success of a movie

In [207]:
data.adult

0        False
1        False
2        False
3        False
4        False
         ...
45461    False
45462    False
45463    False
45464    False
45465    False
Name: adult, Length: 45466, dtype: object

- 1st column adult

In [208]:
data.adult.unique()

array(['False', 'True', ' - Written by Ørnås',
       ' Rune Balot goes to a casino connected to the October corporation to try to wrap up her case once and for all.',
       ' Avalanche Sharks tells the story of a bikini contest that turns into a horrifying affair when it is hit by a shark avalanche.'],
      dtype=object)

 we can see 
 . false, true are in string format
 . 3 rows other than values False,True

In [209]:
# findout what rows are other than False,True
data.loc[~data.adult.isin(["False","True"])]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
19730,- Written by Ørnås,0.065736,/ff9qCepilowshEtG2GYWwzt2bs4.jpg,"[{'name': 'Carousel Productions', 'id': 11176}...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1997-08-20,0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29503,Rune Balot goes to a casino connected to the ...,1.931659,/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg,"[{'name': 'Aniplex', 'id': 2883}, {'name': 'Go...","[{'iso_3166_1': 'US', 'name': 'United States o...",2012-09-29,0,68.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,...,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35587,Avalanche Sharks tells the story of a bikini ...,2.185485,/zaSf5OG7V8X8gqFvly88zDdRm46.jpg,"[{'name': 'Odyssey Media', 'id': 17161}, {'nam...","[{'iso_3166_1': 'CA', 'name': 'Canada'}]",2014-01-01,0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [210]:
# checking for other columns we can see 
# belongs_to_collection cannot be numeric, budget can be numeric, id cannot be data,language cannot be numeric
# DECIDED TO DROP THE ROWS

In [211]:
data=data.loc[data.adult.isin(["False","True"]),:]

In [212]:
data.adult.unique()

array(['False', 'True'], dtype=object)

In [213]:
# false, true are in string format 
# need to convert them into boolean

In [214]:
data.adult=data.adult.map({'True':True,'False':False})

In [215]:
data.adult.unique()

array([False,  True])

In [216]:
data.shape

(45463, 24)

### 2nd column belongs_to_collection

In [217]:
data.belongs_to_collection

0        {'id': 10194, 'name': 'Toy Story Collection', ...
1                                                      NaN
2        {'id': 119050, 'name': 'Grumpy Old Men Collect...
3                                                      NaN
4        {'id': 96871, 'name': 'Father of the Bride Col...
                               ...
45461                                                  NaN
45462                                                  NaN
45463                                                  NaN
45464                                                  NaN
45465                                                  NaN
Name: belongs_to_collection, Length: 45463, dtype: object

In [218]:
data.belongs_to_collection[2]

"{'id': 119050, 'name': 'Grumpy Old Men Collection', 'poster_path': '/nLvUdqgPgm3F85NMCii9gVFUcet.jpg', 'backdrop_path': '/hypTnLot2z8wpFS7qwsQHW1uV8u.jpg'}"

In [219]:
data.belongs_to_collection.isnull().sum()

40972

 - data type of belongs_to_collection is string format dictionary
 problems  need tobe solved - 
 1. convert the string to dictionary (its original form)
 2. extract 'name' from the dictionary
 3. replace NaN value with No Collection (since we have 40972)
 4. replace entire belongs column with collection column

In [220]:
import ast
collections=[]
for i in data.belongs_to_collection:
    if i==i:
        collections.append(ast.literal_eval(i)['name'])
    else:
        collections.append("No collection")

In [221]:
collections

['Toy Story Collection',
 'No collection',
 'Grumpy Old Men Collection',
 'No collection',
 'Father of the Bride Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'James Bond Collection',
 'No collection',
 'No collection',
 'Balto Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Ace Ventura Collection',
 'No collection',
 'Chili Palmer Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Babe Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Mortal Kombat Collection',
 'No collection',
 'No collection',
 'No collection',
 'Pocahontas Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Lawnmower Man Collection',
 'No collection',
 'No collection',
 'Friday Collection',
 'From Dusk Till Dawn Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Screamers Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Muppet Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Neverending Story Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Bad Boys Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Batman Collection',
 'No collection',
 'No collection',
 'Brooklyn Cigar Store Collection',
 'No collection',
 'Casper Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Mexico Trilogy',
 'No collection',
 'Die Hard Collection',
 'Teenage Apocalypse Trilogy',
 'No collection',
 'No collection',
 'Free Willy Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Power Rangers Collection',
 'No collection',
 'No collection',
 'No collection',
 'Síť (kolekce)',
 'No collection',
 'No collection',
 'The Prophecy Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Showgirls Collection',
 'Brooklyn Cigar Store Collection',
 'No collection',
 'Species Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Under Siege Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Burnt by the Sun Trilogy',
 'No collection',
 'Before... Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Clerks Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Dumb and Dumber Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'A Goofy Movie Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Vampire Chronicles',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Star Wars Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Nemesis Collection',
 'No collection',
 'No collection',
 'No collection',
 'Once were Warriors Collection',
 'Poison Ivy Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Three Colors Collection',
 'Three Colors Collection',
 'Three Colors Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Swan Princess Series',
 'No collection',
 'No collection',
 'No collection',
 'The Santa Clause Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Tales from the Crypt Collection',
 'Star Trek: The Next Generation Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Ace Ventura Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Jack Ryan Collection',
 'No collection',
 'No collection',
 'No collection',
 'The Crow Collection',
 'No collection',
 'The Flintstones (Live-Action) Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Lion King Collection',
 'No collection',
 'A Nightmare on Elm Street Collection',
 'The Mask Collection',
 'No collection',
 'No collection',
 'Naked Gun Collection',
 'No collection',
 'No collection',
 'No collection',
 'Richie Rich Collection',
 'No collection',
 'No collection',
 'Speed Collection',
 'No collection',
 'Timecop Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Street Fighter',
 'No collection',
 'No collection',
 'No collection',
 'Fear Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Highlander Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Addams Family Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Stakeout Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Beverly Hills Cop Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'City Slickers Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Endless Summer Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Free Willy Collection',
 'No collection',
 'The Fugitive / U.S. Marshals Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Hard Target Collection',
 'No collection',
 'Hot Shots! Collection',
 'No collection',
 'No collection',
 'No collection',
 'House Party Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Jurassic Park Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Karate Kid Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'RoboCop Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Secret Garden Collection',
 'No collection',
 'The Shadow Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Blade Runner Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Brady Bunch Collection',
 'Home Alone Collection',
 'No collection',
 'Aladdin Collection',
 'The Terminator Collection',
 'No collection',
 'No collection',
 'Batman Collection',
 'The Hannibal Lecter Anthology',
 'No collection',
 'Beauty and the Beast Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Candyman Collection',
 'No collection',
 'No collection',
 'Homeward Bound Collection',
 'Heavy Metal Collection',
 'Hellraiser Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'All Dogs Go to Heaven Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Mission: Impossible Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'DragonHeart Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Bloodsport Collection',
 'The Apu Collection',
 'The Apu Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Lemmy Caution Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Substitute Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Visitors Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Ghost in the Shell Collection',
 'No collection',
 'No collection',
 'No collection',
 'Wallace & Gromit Collection',
 'No collection',
 'No collection',
 'The Arrival Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Martin Scorsese’s World Cinema Project, Vol. 1',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Trainspotting Collection',
 'No collection',
 'Independence Day Collection',
 'No collection',
 'No collection',
 'The Hunchback of Notre Dame Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Nutty Professor Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Brady Bunch Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Crow Collection',
 'No collection',
 'No collection',
 'Tales from the Crypt Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Escape From ... Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Godfather Collection',
 'No collection',
 'Police Story Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Police Story Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Land Before Time Collection',
 'No collection',
 'No collection',
 'Halloween Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Space Odyssey Series',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Thin Man Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Living Dead Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'In the Line of Duty Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'The Mighty Ducks Collection',
 'No collection',
 'The Apple Dumpling Gang Collection',
 'Davy Crockett Collection',
 'Witch Mountain Collection',
 'Herbie Collection',
 'Herbie Collection',
 'No collection',
 'Parent Trap Collection',
 'No collection',
 'Homeward Bound Collection',
 'The Shaggy Dog Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 'Cinderella Collection',
 'No collection',
 'Caballeros Collection',
 'No collection',
 'No collection',
 'No collection',
 'No collection',
 ...]

In [222]:
data['Collections']=collections

In [223]:
data=data.drop(['belongs_to_collection'],axis=1)

In [224]:
data.head()

,adult,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,Collections
0,False,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,Toy Story Collection
1,False,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,No collection
2,False,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,Grumpy Old Men Collection
3,False,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,No collection
4,False,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,Father of the Bride Collection

#### Budget

In [225]:
data.budget.value_counts()[0]

36573

In [226]:
# %of zero values
sum(data.budget=='0')*100/data.shape[0]

80.44563711149726

1. there are 36573 null values in budget column
2. format of budget is not correct
3. 80 percent of budget is not having null values

##### i am not taking budget as a factor for movie success

##### Genre

In [227]:
data.genres[0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [228]:
data.genres.isnull().sum()

0

1. genre is in string dictionary format
2. each movie belongs to multiple genres

##### HomePage

In [229]:
data.homepage.isnull().sum()

37684

In [230]:
data.homepage.isnull()

0        False
1         True
2         True
3         True
4         True
         ...
45461    False
45462     True
45463     True
45464     True
45465     True
Name: homepage, Length: 45463, dtype: bool

In [231]:
data['HomePagePresent']=(~data.homepage.isnull())

In [232]:
data=data.drop(['homepage'],axis=1)

In [233]:
data.head()

,adult,budget,genres,id,imdb_id,original_language,original_title,overview,popularity,poster_path,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,Collections,HomePagePresent
0,False,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,...,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,Toy Story Collection,True
1,False,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,...,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,No collection,False
2,False,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,...,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,Grumpy Old Men Collection,False
3,False,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,...,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,No collection,False
4,False,0,"[{'id': 35, 'name': 'Comedy'}]",11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,...,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,Father of the Bride Collection,False

##### ID

In [234]:
data.shape[0]-len(data.id.unique())

30

In [235]:
data=data.drop_duplicates(subset="id")

In [236]:
data.id.unique()

array(['862', '8844', '15602', ..., '67758', '227506', '461257'],
      dtype=object)

In [237]:
data=data.dropna(subset="id")

In [238]:
data.id

0           862
1          8844
2         15602
3         31357
4         11862
          ...
45461    439050
45462    111109
45463     67758
45464    227506
45465    461257
Name: id, Length: 45433, dtype: object

In [239]:
data.id.dtypes

dtype('O')

In [240]:
# converting to integers
data.id=data.id.astype('int64')

In [241]:
data.id.dtypes

dtype('int64')

##### imbd_id

In [242]:
data.imdb_id[0]

'tt0114709'

In [243]:
data.imdb_id.isnull().sum()

17

1. every movie must have imdb_id
2. it cannot have no imdb_id

In [244]:
# drop duplicates of imdb
data=data.drop_duplicates(subset="imdb_id")

In [245]:
data.shape[0]-len(data.imdb_id.unique())

0

##### original language

In [246]:
data.original_language.unique()

array(['en', 'fr', 'zh', 'it', 'fa', 'nl', 'de', 'cn', 'ar', 'es', 'ru',
       'sv', 'ja', 'ko', 'sr', 'bn', 'he', 'pt', 'wo', 'ro', 'hu', 'cy',
       'vi', 'cs', 'da', 'no', 'nb', 'pl', 'el', 'sh', 'xx', 'mk', 'bo',
       'ca', 'fi', 'th', 'sk', 'bs', 'hi', 'tr', 'is', 'ps', 'ab', 'eo',
       'ka', 'mn', 'bm', 'zu', 'uk', 'af', 'la', 'et', 'ku', 'fy', 'lv',
       'ta', 'sl', 'tl', 'ur', 'rw', 'id', 'bg', 'mr', 'lt', 'kk', 'ms',
       'sq', nan, 'qu', 'te', 'am', 'jv', 'tg', 'ml', 'hr', 'lo', 'ay',
       'kn', 'eu', 'ne', 'pa', 'ky', 'gl', 'uz', 'sm', 'mt', 'hy', 'iu',
       'lb', 'si'], dtype=object)

In [247]:
len(data.original_language.unique())

90

In [248]:
len(data.original_language)

45417

In [249]:
data.original_language.dtypes

dtype('O')

In [250]:
data.original_language.isnull().sum()

11

In [251]:
data.loc[data.original_language.isnull(),:]

,adult,budget,genres,id,imdb_id,original_language,original_title,overview,popularity,poster_path,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,Collections,HomePagePresent
19574,False,0,"[{'id': 99, 'name': 'Documentary'}]",283101,tt0429086,NaN,Shadowing the Third Man,Documentary about the production of The Third ...,0.017007,/xT9csxMKYbizRQgvNzCXJ67R7er.jpg,...,95.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Shadowing the Third Man,False,0.0,0.0,No collection,False
21602,False,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",103902,tt0838231,NaN,Unfinished Sky,An Outback farmer takes in an Afghani woman wh...,0.359818,/vfaJuZF0ocVwBEDYZhoULGuVxrz.jpg,...,94.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Unfinished Sky,False,6.4,8.0,No collection,False
22832,False,0,"[{'id': 10752, 'name': 'War'}, {'id': 37, 'nam...",359195,tt0053558,NaN,13 Fighting Men,A group of Union Army soldiers is charged with...,0.070647,/q5ADXvvzYtAOyrReIg1HckdPj62.jpg,...,69.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,13 Fighting Men,False,0.0,0.0,No collection,False
32141,False,0,"[{'id': 35, 'name': 'Comedy'}]",147050,tt0122580,NaN,Lambchops,George and Gracie enter an elegant drawing roo...,0.073418,/upQByEwY58sHWdL3RZm7kmRc44s.jpg,...,8.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Lambchops,False,6.5,2.0,No collection,False
37407,False,0,"[{'id': 16, 'name': 'Animation'}]",257095,tt0225145,NaN,Bajaja,The first fairy tale transformed into a full-l...,0.036841,/12wf2EkrPGxNzRbNyoau8GIFp3M.jpg,...,87.0,"[{'iso_639_1': 'cs', 'name': 'Český'}]",Released,NaN,Prince Bayaya,False,5.0,1.0,No collection,False
41047,False,0,"[{'id': 99, 'name': 'Documentary'}]",332742,tt4432912,NaN,Song of Lahore,"Until the late 1970s, the Pakistani city of La...",0.373688,/6iJqscs2xQLKKvrTCWmlHd9rf3W.jpg,...,82.0,"[{'iso_639_1': 'ur', 'name': 'اردو'}, {'iso_63...",Released,NaN,Song of Lahore,False,6.5,2.0,No collection,False
41872,False,0,"[{'id': 99, 'name': 'Documentary'}]",144410,tt0154152,NaN,Annabelle Serpentine Dance,Two dancers perform in succession facing a sta...,1.58434,/l7Lzvah6PL6vdMF5p0elKiyYqp9.jpg,...,1.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,NaN,Annabelle Serpentine Dance,False,5.7,20.0,No collection,False
44057,False,0,"[{'id': 18, 'name': 'Drama'}]",380438,tt0298411,NaN,Lettre d'une inconnue,NaN,0.001283,/gk32ZWTYgfTXctEyCDAWeMcxo7X.jpg,...,0.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,Lettre d'une inconnue,False,0.0,0.0,No collection,False
44410,False,0,"[{'id': 16, 'name': 'Animation'}, {'id': 99, '...",381096,tt5333518,NaN,Garn,The traditional crafts of crochet and knitting...,0.067624,/olEOCEGTW15WBPC0UnmLjokrmNF.jpg,...,76.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}, {'iso...",Released,NaN,Yarn,False,0.0,0.0,No collection,False
44576,False,0,[],381525,tt5376720,NaN,WiNWiN,American investment fund buys Austrian compani...,0.030766,/pErCRQoc3nt8lCsExd3fFYgyBox.jpg,...,84.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,WiNWiN,False,0.0,0.0,No collection,False
44655,False,0,"[{'id': 28, 'name': 'Action'}, {'id': 10752, '...",104473,tt0223958,NaN,La prise de Tournavos,"Three military men, seen inside a fortificatio...",0.471325,/4VmQBE9qBRxCE3gHtSAa5AUsURq.jpg,...,1.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Rumored,NaN,The Surrender of Tournavos,False,4.6,5.0,No collection,False

In [252]:
data.original_language=data.original_language.fillna('mode')

In [253]:

data.loc[data.original_language.isnull(),:]

Empty DataFrame
Columns: [adult, budget, genres, id, imdb_id, original_language, original_title, overview, popularity, poster_path, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, status, tagline, title, video, vote_average, vote_count, Collections, HomePagePresent]
Index: []

[0 rows x 24 columns]

##### original_title

In [254]:
data.shape[0]-len(data.original_title.unique())

2060

In [255]:
(data.original_title.isnull().sum())

0

In [256]:
len(data.original_title.unique())

43357

In [257]:
data.original_title=data.original_title.str.strip()

In [258]:
data.original_title=data.original_title.str.lower()

In [259]:
data.original_title

0                          toy story
1                            jumanji
2                   grumpier old men
3                  waiting to exhale
4        father of the bride part ii
                    ...
45461                        رگ خواب
45462            siglo ng pagluluwal
45463                       betrayal
45464            satana likuyushchiy
45465                       queerama
Name: original_title, Length: 45417, dtype: object

##### overview

In [260]:
data.shape[0]-len(data.overview.unique())

1124

In [261]:
data.overview.isnull().sum()

952

In [262]:
data.loc[data.overview.isnull(),:]

,adult,budget,genres,id,imdb_id,original_language,original_title,overview,popularity,poster_path,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,Collections,HomePagePresent
32,False,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 12, ...",78802,tt0114952,fr,"guillaumet, les ailes du courage",NaN,0.745542,/k6ODtR38dKEfuzSGjggr8KDyAF4.jpg,...,50.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Wings of Courage,False,6.8,4.0,No collection,False
300,False,22000000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",161495,tt0114296,sv,roommates,NaN,3.395867,/hvHNlMvWS2GBt7RR971bJ3k4bJc.jpg,...,108.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Roommates,False,6.4,7.0,No collection,False
634,False,0,"[{'id': 35, 'name': 'Comedy'}]",287305,tt0117312,de,peanuts – die bank zahlt alles,NaN,0.066123,/wpk30SvRHmjC2plgKHZXxG0FlKd.jpg,...,NaN,[],Released,NaN,Peanuts – Die Bank zahlt alles,False,4.0,1.0,No collection,False
635,False,0,"[{'id': 35, 'name': 'Comedy'}]",339428,tt0116485,de,happy weekend,NaN,0.002229,NaN,...,NaN,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,NaN,Happy Weekend,False,0.0,0.0,No collection,False
641,False,0,"[{'id': 35, 'name': 'Comedy'}]",10801,tt0117788,de,das superweib,NaN,0.821299,/AbhMKCh3fV5PY2B9uSPF1DWEvq2.jpg,...,86.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,NaN,The Superwife,False,5.3,7.0,No collection,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45342,False,0,"[{'id': 18, 'name': 'Drama'}]",199887,tt1771636,en,over/under,NaN,0.704642,/1xLaIBGGPE4APtBJdfeuyOWICZ0.jpg,...,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Over/Under,False,4.0,2.0,No collection,False
45377,False,0,"[{'id': 12, 'name': 'Adventure'}]",317389,tt0070695,es,simbad e il califfo di bagdad,NaN,0.006352,/izk7KbT6LZO9baEhCkOZYMgj60w.jpg,...,NaN,"[{'iso_639_1': 'it', 'name': 'Italiano'}]",Released,NaN,Simbad e il califfo di Bagdad,False,0.0,0.0,No collection,False
45398,False,1254040,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",468707,tt5742932,fi,lauri mäntyvaaran tuuheet ripset,NaN,0.347806,/rKOpJuwb7pTqYVShHM2tl25VxyF.jpg,...,90.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,NaN,Thick Lashes of Lauri Mäntyvaara,False,8.0,1.0,No collection,True
45399,False,750000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",280422,tt3805180,ru,все и сразу,NaN,0.201582,/hNsmPpl3zLG36jr4EIEd5P8I4pa.jpg,...,0.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",Released,NaN,All at Once,False,6.0,4.0,No collection,False
45410,False,0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",449131,tt0321264,ru,aprel,NaN,0.008903,NaN,...,NaN,[],Released,NaN,Aprel,False,6.0,1.0,No collection,False

In [263]:
data.overview=data.overview.fillna('no overview available')

In [264]:
data.loc[data.overview.isnull(),:]

Empty DataFrame
Columns: [adult, budget, genres, id, imdb_id, original_language, original_title, overview, popularity, poster_path, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, status, tagline, title, video, vote_average, vote_count, Collections, HomePagePresent]
Index: []

[0 rows x 24 columns]

##### popularity

In [265]:
data.popularity.isnull().sum()

3

In [266]:
data.popularity.dtypes

dtype('O')

In [267]:
data.popularity=data.popularity.astype('float64')

In [268]:
data.loc[data.popularity.isnull(),:]

,adult,budget,genres,id,imdb_id,original_language,original_title,overview,popularity,poster_path,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,Collections,HomePagePresent
19729,False,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",82663,tt0113002,en,midnight man,British soldiers force a recently captured IRA...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No collection,False
29502,False,0,"[{'id': 16, 'name': 'Animation'}, {'id': 878, ...",122662,tt2423504,ja,マルドゥック・スクランブル 排気,Third film of the Mardock Scramble series.,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mardock Scramble Collection,True
35586,False,0,"[{'id': 10770, 'name': 'TV Movie'}, {'id': 28,...",249260,tt2622826,en,avalanche sharks,A group of skiers are terrorized during spring...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No collection,False

1. popularity null values have no vote_average, vote_count

In [269]:
data=data.dropna(subset="popularity")

In [270]:
data.loc[data.popularity.isnull(),:]

Empty DataFrame
Columns: [adult, budget, genres, id, imdb_id, original_language, original_title, overview, popularity, poster_path, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, status, tagline, title, video, vote_average, vote_count, Collections, HomePagePresent]
Index: []

[0 rows x 24 columns]

##### poster path

In [271]:
# poster path does not make difference in success of movie

In [272]:
data=data.drop(["poster_path"],axis=1)

##### run time

In [283]:
data.runtime[0:10]

0     81.0
1    104.0
2    101.0
3    127.0
4    106.0
5    170.0
6    127.0
7     97.0
8    106.0
9    130.0
Name: runtime, dtype: float64

In [284]:
data.runtime.isnull().sum()

255

In [285]:
data.loc[data.runtime.isnull(),:]

,adult,budget,genres,id,imdb_id,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,Collections,HomePagePresent
634,False,0,"[{'id': 35, 'name': 'Comedy'}]",287305,tt0117312,de,peanuts – die bank zahlt alles,no overview available,0.066123,"[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...",...,NaN,[],Released,NaN,Peanuts – Die Bank zahlt alles,False,4.0,1,No collection,False
635,False,0,"[{'id': 35, 'name': 'Comedy'}]",339428,tt0116485,de,happy weekend,no overview available,0.002229,"[{'name': 'Senator Film Produktion', 'id': 191}]",...,NaN,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,NaN,Happy Weekend,False,0.0,0,No collection,False
644,False,0,"[{'id': 18, 'name': 'Drama'}]",278978,tt0118026,de,und keiner weint mir nach,no overview available,0.439989,[],...,NaN,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,NaN,Und keiner weint mir nach,False,0.0,0,No collection,False
802,False,0,"[{'id': 18, 'name': 'Drama'}]",282919,tt0112865,de,diebinnen,no overview available,0.106345,[],...,NaN,[],Released,NaN,Diebinnen,False,4.0,1,No collection,False
863,False,0,"[{'id': 53, 'name': 'Thriller'}]",253632,tt0094822,fr,baton rouge,no overview available,0.437895,[],...,NaN,[],Released,NaN,Baton Rouge,False,0.0,0,No collection,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45246,False,0,"[{'id': 35, 'name': 'Comedy'}]",231216,tt0441908,de,villa henriette,no overview available,0.002513,[],...,NaN,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,NaN,Villa Henriette,False,0.0,0,No collection,False
45310,False,0,[],418757,tt4112020,pl,między nami dobrze jest,no overview available,0.030803,[],...,NaN,[],Released,NaN,Między nami dobrze jest,False,0.0,0,No collection,False
45313,False,0,"[{'id': 18, 'name': 'Drama'}]",369444,tt0098035,pl,ostatni dzwonek,no overview available,0.000102,[],...,NaN,[],Released,NaN,Ostatni dzwonek,False,0.0,0,No collection,False
45377,False,0,"[{'id': 12, 'name': 'Adventure'}]",317389,tt0070695,es,simbad e il califfo di bagdad,no overview available,0.006352,"[{'name': 'Roas Produzioni', 'id': 21137}, {'n...",...,NaN,"[{'iso_639_1': 'it', 'name': 'Italiano'}]",Released,NaN,Simbad e il califfo di Bagdad,False,0.0,0,No collection,False
45410,False,0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",449131,tt0321264,ru,aprel,no overview available,0.008903,[],...,NaN,[],Released,NaN,Aprel,False,6.0,1,No collection,False

In [288]:
data.loc[data.runtime==0,'runtime']=90

In [289]:
data.runtime.isnull().sum()

255

##### spoken_languages

In [294]:
data.spoken_languages[99]

"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso_639_1': 'en', 'name': 'English'}]"

In [296]:
Total_Languages=[]
for i in data.spoken_languages.values:
    prod=ast.literal_eval(i)
    Total_Languages.append(len(prod))

In [298]:
data['Total_languages']=Total_Languages

In [299]:
data=data.drop(["spoken_languages"],axis=1)

In [300]:
data

,adult,budget,genres,id,imdb_id,original_language,original_title,overview,popularity,production_companies,...,runtime,status,tagline,title,video,vote_average,vote_count,Collections,HomePagePresent,Total_languages
0,False,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,tt0114709,en,toy story,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]",...,81.0,Released,NaN,Toy Story,False,7.7,5415,Toy Story Collection,True,1
1,False,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,tt0113497,en,jumanji,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",...,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413,No collection,False,2
2,False,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,tt0113228,en,grumpier old men,A family wedding reignites the ancient feud be...,11.712900,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",...,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92,Grumpy Old Men Collection,False,1
3,False,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,tt0114885,en,waiting to exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,...,127.0,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34,No collection,False,1
4,False,0,"[{'id': 35, 'name': 'Comedy'}]",11862,tt0113041,en,father of the bride part ii,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...",...,106.0,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173,Father of the Bride Collection,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,0.072051,[],...,90.0,Released,Rising and falling between a man and woman,Subdue,False,4.0,1,No collection,True,1
45462,False,0,"[{'id': 18, 'name': 'Drama'}]",111109,tt2028550,tl,siglo ng pagluluwal,An artist struggles to finish his work while a...,0.178241,"[{'name': 'Sine Olivia', 'id': 19653}]",...,360.0,Released,NaN,Century of Birthing,False,9.0,3,No collection,False,1
45463,False,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,tt0303758,en,betrayal,"When one of her hits goes wrong, a professiona...",0.903007,"[{'name': 'American World Pictures', 'id': 6165}]",...,90.0,Released,A deadly game of wits.,Betrayal,False,3.8,6,No collection,False,1
45464,False,0,[],227506,tt0008536,en,satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,"[{'name': 'Yermoliev', 'id': 88753}]",...,87.0,Released,NaN,Satan Triumphant,False,0.0,0,No collection,False,0
45465,False,0,[],461257,tt6980792,en,queerama,50 years after decriminalisation of homosexual...,0.163015,[],...,75.0,Released,NaN,Queerama,False,0.0,0,No collection,False,1

##### status

In [301]:
data.status.value_counts()

Released           44971
Rumored              227
Post Production       98
In Production         20
Planned               15
Canceled               2
Name: status, dtype: int64

In [302]:
data.status.isnull().sum()

81

In [303]:
data.loc[data.status.isnull(),:]

,adult,budget,genres,id,imdb_id,original_language,original_title,overview,popularity,production_companies,...,runtime,status,tagline,title,video,vote_average,vote_count,Collections,HomePagePresent,Total_languages
189,False,0,"[{'id': 99, 'name': 'Documentary'}]",56088,tt0114435,en,the show,A documentary about the culture of hip-hop. Th...,0.159596,[],...,93.0,NaN,What Happens On Stage Is Only Half The Story!,The Show,False,5.3,2,No collection,False,0
767,False,0,"[{'id': 99, 'name': 'Documentary'}]",52059,tt0113147,en,the gate of heavenly peace,The Gate of Heavenly Peace is a feature-length...,0.107050,[],...,180.0,NaN,NaN,The Gate of Heavenly Peace,False,6.7,3,No collection,True,0
1384,False,0,"[{'id': 35, 'name': 'Comedy'}]",40506,tt0119644,en,meet wally sparks,Wally Sparks is a tabloid TV show reporter who...,0.576741,[],...,105.0,NaN,NaN,Meet Wally Sparks,False,5.3,10,No collection,False,1
2140,False,0,[],77314,tt0101530,fr,the cabinet of dr. ramirez,no overview available,0.037500,[],...,NaN,NaN,NaN,The Cabinet of Dr. Ramirez,False,0.0,0,No collection,False,0
3460,False,0,"[{'id': 18, 'name': 'Drama'}]",94214,tt0210130,en,"jails, hospitals & hip-hop","Jails, Hospitals &amp; Hip-Hop is a cinematic ...",0.009057,[],...,90.0,NaN,three worlds / two million voices / one genera...,"Jails, Hospitals & Hip-Hop",False,0.0,0,No collection,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44377,False,0,[],39827,tt0131064,en,the who: thirty years of maximum r&b,A celebration of 30 years of The Who.,0.014260,[],...,155.0,NaN,NaN,The Who: Thirty Years of Maximum R&B,False,0.0,0,No collection,False,0
45067,False,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",49492,tt1653015,en,jogwa - the awakening,"Jogwa actually means alms given to a person, u...",0.004990,[],...,92.0,NaN,The Awakening,Jogwa - The Awakening,False,0.0,0,No collection,False,0
45090,False,0,[],128268,tt0876565,en,veruschka - die inszenierung (m)eines körpers,Documentary about Veruschka von Lehndorff.,0.056298,[],...,52.0,NaN,NaN,Veruschka: A Life for the Camera,False,6.0,1,No collection,False,2
45159,False,0,[],41811,tt0099480,en,eating,"At a spacious house in Los Angeles, Helene is ...",0.000002,[],...,110.0,NaN,NaN,Eating,False,0.0,0,No collection,False,1
45442,False,0,[],44330,tt0135690,en,le tripot clandestin,A combination gambling den and bawdy house is ...,0.219260,[],...,3.0,NaN,NaN,The Scheming Gambler's Paradise,False,5.0,3,No collection,False,0

##### vote_average

In [274]:
data.vote_average.isnull().sum()

0

In [275]:
data.vote_average.dtypes

dtype('float64')

##### vote_count

In [277]:
data.vote_count.isnull().sum()

0

In [278]:
data.vote_count.dtypes

dtype('float64')

In [279]:
data.vote_count=data.vote_count.astype('int64')